services:
  cypress-tests:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    environment:
      - CYPRESS_baseUrl=http://localhost:8000
      - CI=true
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --browser electron --reporter cypress-mochawesome-reporter"
    
  cypress-unit:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --spec 'cypress/e2e/unit/**/*.cy.js' --browser electron"
    
  cypress-integration:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --spec 'cypress/e2e/integration/**/*.cy.js' --browser electron"
    
  cypress-memory:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --spec 'cypress/e2e/memory/**/*.cy.js' --browser electron"
    
  cypress-performance:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --spec 'cypress/e2e/performance/**/*.cy.js' --browser electron"
    
  # Basic test that should work
  cypress-basic:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             npx cypress run --spec 'cypress/e2e/unit/basic-page-test.cy.js' --browser electron"

  # Development service for interactive testing
  cypress-dev:
    build:
      context: .
      dockerfile: Dockerfile.cypress.simple
    volumes:
      - ./cypress:/app/cypress
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/reports:/app/cypress/reports
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=${DISPLAY:-:0}
    command: >
      sh -c "python3 -m http.server 8000 &
             sleep 5 &&
             echo 'Server started at http://localhost:8000' &&
             echo 'Run: docker exec -it <container> npx cypress open' &&
             tail -f /dev/null"
